version: '3.8'

services:
  belegmeister:
    build: .
    ports:
      - "5031:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./receipts:/app/receipts
      - ./reimbursements:/app/reimbursements
      - ./logs:/app/logs
      - belegmeister_data:/app/data
    environment:
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  belegmeister_data: